import discord
from dalle2 import Dalle2
import requests
from io import BytesIO
import helper
import db_manager
from discord.ext import commands, bridge
import permission_manager as perm

################ Module Start ################

dalle = Dalle2("sess-M7IQmDZQIDuUNByQvwZQPQazYZxUnUXm6fZupg5l")

class Dalle(commands.Cog):
    def __init__(self, client):
        self.client = client

    metadata = {
        'emoji': ':robot:',
        'name': 'Dalle-2 AI',
        'description': 'Generates an AI image from text',
        'aliases': ['dalle', 'ai'],
        'permission_level': 'Member',
    }
    
    @bridge.bridge_command(name="dalle2", aliases=metadata['aliases'], description=metadata['description'])
    async def dallecmd(self, ctx, prompt: discord.Option(str, description="The prompt to generate an image from", required=True)):

        if ctx.channel.id != 951037482173075497 and ctx.author.id != 268974144593461248:
            forbidden_embed = discord.Embed(
                title=':x: Error',
                description='This command can only be used in <#951037482173075497>.',
                color=0xff0000
            )
            await ctx.reply(embed=forbidden_embed)
            return

        if db_manager.fetch_coin_balance(ctx.author)[0] < 100:
            error_embed = discord.Embed(
                title=':x: No dollas',
                description='You are {} coins short.'.format(
                    10 - db_manager.fetch_coin_balance(ctx.author)[0]),
                color=0xff0000
            )

            error_embed.set_footer(text='You need 100 coins to use this command.')

            await ctx.reply(embed=error_embed)
            return

        db_manager.update_coin_balance(ctx.author.id, -100)
        db_manager.new_transaction(trans_type='COMMAND',
                                recip_username=ctx.author.name,
                                recip_id=ctx.author.id,
                                recip_newbal=db_manager.fetch_coin_balance(ctx.author)[0],
                                sender_username='DALL-E',
                                sender_id=0,
                                sender_newbal=0,
                                amount=-100,
                                note='Used DALL-E command')

        try:

            embed = discord.Embed(
                title=':mag: Dalle AI',
                description='Generating...',
                color=0x9e9e9e
            ).add_field(
                name='Query',
                value=prompt
            )

            dalle_embed = await ctx.reply(embed=embed)

            generations = dalle.generate(prompt)

            await dalle_embed.delete_original_response()

            photo_embeds = []

            for generation in generations:
                url = generation['generation']['image_path']

                photo = discord.Embed(
                    title='Results [Dall-E]',
                    description=f'**Query:**\n{prompt}',
                    url='https://cdn.discordapp.com/'
                ).set_image(url=url).set_footer(text=f'Generated by: {ctx.author.display_name} | {db_manager.fetch_coin_balance(ctx.author)[0]} coins remaining')

                photo_embeds.append(photo)

            await ctx.reply(embeds=photo_embeds)
            return

        except Exception as e:
            print(e)
            query_error_embed = discord.Embed(
                title=':x: Error',
                description='Failed to generate image. The server returned:\n```{}```'.format(
                    e),
                color=0xff0000
            )
            await ctx.channel.send(embed=query_error_embed)
            return

    ################ Module End ################

def setup(client):
    client.add_cog(Dalle(client))